name: "🚀 Feature Request"
description: "Propose a new feature for project with comprehensive details"
title: "[Feature]: "
labels:
  - feature-request
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        ## 📋 Feature Request Guidelines
        Please provide detailed information about the proposed feature.
  - type: textarea
    id: feature-summary
    attributes:
      label: "🌟 Feature Summary"
      description: "Provide a clear, concise summary of the feature"
      placeholder: "Brief description of the proposed feature"
    validations:
      required: true
  - type: textarea
    id: feature-objectives
    attributes:
      label: "🎯 Feature Objectives"
      description: "Describe the primary objectives and expected user benefits"
      placeholder: |
        - Objective 1
        - Objective 2
    validations:
      required: true
  - type: checkboxes
    id: technology-stack
    attributes:
      label: "🔧 Predefined Technology Stack"
      description: "Confirm the technology stack for this feature"
      options:
        - label: Frontend Framework - Next.js (React)
          default: true
        - label: Backend - Next.js API Routes / Serverless Functions
          default: true
        - label: Programming Language - TypeScript
          default: true
        - label: Styling - Tailwind CSS
          default: true
        - label: UI Component Library - Shadcn/UI
          default: true
        - label: Form Handling - React Hook Form
          default: true
        - label: Validation - Zod
          default: true
        - label: Authentication - NextAuth.js
          default: true
        - label: Database - Prisma with PostgreSQL
          default: true
        - label: Deployment - Vercel
          default: true
    validations:
      required: true
